USE [ES]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Значения_связи](
	[ID_СП] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ID_Связи] [numeric](18, 0) NULL,
	[ID_ПП] [numeric](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_СП] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


