USE [ES]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Переменные_предикаты](
	[ID_ПП] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Значение] [varchar](50) NULL,
	[Наименование] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ПП] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


