USE [ES]
GO

CREATE LOGIN [Guest] WITH PASSWORD=N'TestPass', DEFAULT_DATABASE=[ES], DEFAULT_LANGUAGE=[русский], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

ALTER LOGIN [Guest] ENABLE
GO

CREATE USER [Guest] FOR LOGIN [Guest]
GO