USE [master]
GO

CREATE LOGIN [User] WITH PASSWORD=N'gvNZ80hnJuwPLfTQg2trRzbjyXIsbhDrPvRTzv+JRYQ=', DEFAULT_DATABASE=[ES], DEFAULT_LANGUAGE=[русский], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

ALTER LOGIN [User] DISABLE
GO
